# model_settings.yaml
# Configuration for model execution on CPU or NPU with unique IDs

# Available models:
# - yolov3_big
# - yolov3_small
# - resnet50_small
# - resnet50_big

# Model-execution configurations with unique IDs
combination1:
  # YOLO models on CPU
  yolo_big_cpu:
    model: yolov3_big
    execution: cpu
    display: view1

  # ResNet models on CPU
  resnet50_small_cpu:
    model: resnet50_small
    execution: cpu
    display: view2

  # YOLO models on NPU
  yolo_small_npu:
    model: yolov3_big
    execution: cpu
    display: view3

  resnet50_small_npu:
    model: resnet50_small
    execution: cpu
    display: view4

combination2:
  # YOLO models on CPU
  yolo_big_cpu:
    model: yolov3_big
    execution: cpu
    display: view1

  # ResNet models on CPU
  resnet50_small_cpu:
    model: resnet50_small
    execution: cpu
    display: view2

  # YOLO models on NPU
  yolo_small_npu:
    model: yolov3_big
    execution: npu0
    display: view3

  # ResNet models on NPU
  resnet50_small_npu:
    model: resnet50_small
    execution: npu1
    display: view4
