# model_settings.yaml
# Configuration for model execution on CPU or NPU with unique IDs

# Available models:
# - yolov3_big
# - yolov3_small
# - resnet50

# Model-execution configurations with unique IDs
combinations:
  # YOLO models on CPU
  yolo_big_cpu:
    id: 1
    model: yolov3_big
    execution: cpu
    display: view1
  
  yolo_small_cpu:
    id: 2
    model: yolov3_small
    execution: cpu
    display: view3
  
#  # YOLO models on NPU
#  yolo_big_npu0:
#    id: 3
#    model: yolov3_big
#    execution: npu0
#    display: view1
#
#  yolo_small_npu0:
#    id: 4
#    model: yolov3_small
#    execution: npu0
#    display: view3
  
  # ResNet models on CPU
  resnet50_small_cpu:
    id: 5
    model: resnet50_small
    execution: cpu
    display: view2

  # ResNet models on CPU
  resnet50_big_cpu:
    id: 5
    model: resnet50_big
    execution: cpu
    display: view4

#
#  resnet50_small_npu:
#    id: 5
#    model: resnet50
#    execution: npu
#    display: view2
#
#  # ResNet models on CPU
#  resnet50_big_npu:
#    id: 5
#    model: resnet50
#    execution: cnpu
#    display: view4
#
