# model_settings.yaml
# Configuration for model execution on CPU or NPU with unique IDs

# Available models:
# - yolov3_big
# - yolov3_small
# - resnet50

# Model-execution configurations with unique IDs
combinations:
  # YOLO models on CPU
  yolo_big_cpu:
    id: 1
    model: yolov3_big
    execution: cpu
  
  yolo_small_cpu:
    id: 2
    model: yolov3_small
    execution: cpu
  
  # YOLO models on NPU
  yolo_big_npu:
    id: 3
    model: yolov3_big
    execution: npu
  
  yolo_small_npu:
    id: 4
    model: yolov3_small
    execution: npu
  
  # ResNet models on CPU
  resnet50_cpu:
    id: 5
    model: resnet50
    execution: cpu
  
  # ResNet models on NPU
  resnet50_npu:
    id: 6
    model: resnet50
    execution: npu