"""tab:policy-comparison (Table 5, A3). Source analysis/a3_policy_comparison.csv.
Reproduces the 5 representative rows x {P1/P2, P3(theta80), P4, Oracle} with worst(regret)."""
from __future__ import annotations
import sys
import pandas as pd
from pathlib import Path  # [reproduction] path adjusted
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))  # [reproduction] path adjusted
from _common import ANALYSIS, RD, backup_stale

ANALYSIS = Path(__file__).resolve().parent / "data"  # [reproduction] path adjusted (read ./data/a3_policy_comparison.csv)
PKG = Path(__file__).resolve().parent  # [reproduction] path adjusted (write outputs into ./)
REP = [("ResNet k=1", r"\Lcnn{} (24\%)"), ("ResNet k=3", r"ResNet (52\%)"),
       ("ResNet k=8", r"ResNet (67\%)"), ("L2LM", r"\Llm{} (83\%)"), ("L3VLM", r"\Lvlm{} (100\%)")]
DAG = {"L2LM"}  # dagger footnote on P3 at L2LM (co-tenant-only util proxy)


def main():
    d = pd.read_csv(ANALYSIS / "a3_policy_comparison.csv")

    def get(pt, pol):
        r = d[(d.point == pt) & (d.policy == pol)].iloc[0]
        return float(r.worst_sap), float(r.regret)

    PKG.mkdir(exist_ok=True)
    tex = [r"% regenerated by regen_table_policy_comparison.py from a3_policy_comparison.csv",
           r"\begin{tabular}{lccc|c}", r"\toprule",
           r"contention point & P1/P2 acc./lat. & P3 util-$\theta$ & P4 DM-aware & Oracle worst \\",
           r"\midrule"]
    csv_rows = []
    for pt, lbl in REP:
        w1, r1 = get(pt, "P1_isolated_accuracy")
        w3, r3 = get(pt, "P3_util_theta80")
        w4, r4 = get(pt, "P4_deadline_miss_aware")
        ow, _ = get(pt, "Oracle")
        dag = "$^\\dagger$" if pt in DAG else ""
        tex.append(f"{lbl} & {w1:.3f} ({r1:+.3f}) & {w3:.3f} ({r3:+.3f}){dag} & "
                   f"{w4:.3f} ({r4:+.3f}) & {ow:.3f} \\\\")
        csv_rows.append({"point": pt, "P1P2_worst": w1, "P1P2_regret": r1,
                         "P3_worst": w3, "P3_regret": r3, "P4_worst": w4, "P4_regret": r4,
                         "oracle_worst": ow})
    tex += [r"\bottomrule", r"\end{tabular}"]
    backup_stale(PKG / "policy_comparison.tex")
    (PKG / "policy_comparison.tex").write_text("\n".join(tex) + "\n")
    pd.DataFrame(csv_rows).to_csv(PKG / "policy_comparison.csv", index=False)
    # footnote provenance values
    (PKG / "footnote_values.txt").write_text(
        "L2LM P3 utilization = co-tenant-only proxy 49.5% (cpuload_raw.csv)\n"
        "k=1 boundary: mean GPU util 69.7 +/- 2.9%, exceeds 70% in 4/10 runs "
        "(rev30_canonical.csv; see analysis/a3_k1_boundary_check.md)\n")
    print("table_policy_comparison rows:")
    for r in csv_rows:
        print(f"  {r['point']:11s} P1/P2 {r['P1P2_worst']:.3f}({r['P1P2_regret']:+.3f})  "
              f"P4 {r['P4_worst']:.3f}({r['P4_regret']:+.3f})  Oracle {r['oracle_worst']:.3f}")
    return True


if __name__ == "__main__":
    main()
