"""Run manifest for the compare_platforms_v2 basis split + reference cleanup."""
import hashlib
import json
import subprocess
from datetime import datetime
from pathlib import Path

ROOT = Path("/home/msyu/PycharmProjects/multimodel-scheduling-mobilint")
OUT = Path(__file__).resolve().parent
A = "xgboost_model/full_collection_540/analysis"
S = "xgboost_model/full_collection_540/scripts"

MODIFIED = [
    f"{S}/compare_platforms_v2.py",
    f"{A}/platform_divergence.md",
    f"{A}/platform_divergence.csv",
    f"{A}/platform_divergence_raw_v1.md",
    f"{A}/platform_divergence_raw_v1.csv",
    f"{A}/SUMMARY.md",
]
INPUTS = [
    "runs/20260730_190154_score_basis_audit/build_basis_audit.py",
    "runs/20260730_190154_score_basis_audit/divergence_by_group.csv",
    "xgboost_model/full_collection_540/cpu_gpu/performance_gpu_full540.json",
    "xgboost_model/full_collection_540/cpu_npu/performance_npu_full540.json",
]


def sha256(p: Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()


def main():
    verif = json.loads((OUT / "verification.json").read_text())
    m = {
        "run_id": OUT.name,
        "purpose": ("Remove the write collision between the raw-basis P2 generator and "
                    "the v2 declared-basis artifacts, and reconcile the stale references "
                    "reported by runs/20260730_192257_fig_divergence_v2"),
        "executed_at": datetime.now().astimezone().isoformat(timespec="seconds"),
        "git_commit": subprocess.run(["git", "rev-parse", "HEAD"], cwd=ROOT,
                                     capture_output=True, text=True).stdout.strip(),
        "git_branch": subprocess.run(["git", "rev-parse", "--abbrev-ref", "HEAD"], cwd=ROOT,
                                     capture_output=True, text=True).stdout.strip(),
        "git_commit_note": "HEAD at execution time (outputs committed on top of it)",
        "changes": {
            "compare_platforms_v2.py": [
                "added --basis {declared_normalized,raw}, default declared_normalized",
                "declared path imports normalize()/score()/tie_sets() from the audit run's "
                "build_basis_audit.py instead of reimplementing the score",
                "asserts the declared disagreement set against the audit run's "
                "divergence_by_group.csv for BOTH betas before writing anything",
                "replaced the first-max argmax with the 1e-9 tie-set rule in both modes",
                "basis-scoped disjoint output paths + a hard assert that a mode cannot "
                "write the other mode's stem",
                "both modes record score_basis (and generator) in the md provenance header",
                "added --generated-at so re-runs are byte-comparable",
                "raw mode keeps the v1 csv column schema and v1 row order so the preserved "
                "artifact is reproduced instead of being replaced by the unified schema",
            ],
            "SUMMARY.md": [
                "P2 headline row now reports the declared basis (11/45, 16/45, 5 flip "
                "groups, gen 10/33, vision 1/12) and points raw 29/45 / 30/45 at "
                "platform_divergence_raw_v1.*",
                "decision #6 revised to the declared basis, citing the audit run; the "
                "original wording is retained verbatim as a '개정 이력' sub-bullet",
                "P2 output-path row lists both bases and the --basis flag",
            ],
            "platform_divergence_raw_v1.md": [
                "self-reference on the last line now points at "
                "platform_divergence_raw_v1.csv (was platform_divergence.csv)",
                "regenerated by --basis raw, so it also carries the basis warning and the "
                "original_generation provenance of the 2026-07-29 run",
            ],
        },
        "outputs_modified": [{"path": p, "sha256": sha256(ROOT / p),
                              "bytes": (ROOT / p).stat().st_size} for p in MODIFIED],
        "input_artifacts": [{"path": p, "sha256": sha256(ROOT / p),
                             "bytes": (ROOT / p).stat().st_size} for p in INPUTS],
        "verification": verif,
        "unknowns": [],
    }
    (OUT / "run_manifest.json").write_text(json.dumps(m, indent=2, ensure_ascii=False) + "\n")
    print(json.dumps(verif, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
